name: atom_dart
dependencies:
  atom:
    git: git@github.com:DirectMyFile/atom.dart
  logging: any
transformers:
- $dart2js:
    checked: true
    commandLineOptions: [--show-package-warnings]
    csp: true
    minify: false
- atom
