name: atom_dart
dependencies:
  atom:
    git: https://github.com/DirectMyFile/atom.dart.git
  logging: any
  path: any
transformers:
- $dart2js:
    checked: true
    commandLineOptions: [--show-package-warnings]
    csp: true
    minify: false
- atom
